### ISSUE TITLE
TypeError: Object #<Delegate> has no method 'implement'

### ISSUE THREAD

**Issue by elmurci** [petermetz/cordova-proximity-quickstart#4]
Hi,

I just downloaded this quickstart example but can't get it to work:

TypeError: Object #<Delegate> has no method 'implement'
    at new <anonymous> (file:///android_asset/www/ranging/RangingCtrl.js:27:65)

Any ideas?

Thanks

**Comment by brutalbrian** [comment]
I'm having exactly the same problem!

Peter: any comments/fixes/thoughts?

Thanks

**Comment by petermetz** [comment]
@brutalbrian It's because the plugin itself has been updated but I didn't have time to follow through with it in this repository, so the code is not compatible with the latest version of the plugin.

You could either downgrade to an older version of the plugin, like 3.1.2 or just have a look at the updated code examples and change this repo's code accordingly to make it compatible with the latest version.

**Comment by petermetz** [comment]
The code has been updated to match the latest available version of the [proximity plugin](https://github.com/petermetz/cordova-plugin-ibeacon).
Please give it a try and if other problems arise, open a separate issue here on GitHub.


Thanks,
Peter
