### ISSUE TITLE
Blank Tab

### ISSUE THREAD

**Issue by adrianmkofficial** [petermetz/cordova-proximity-quickstart#9]
Hi,

I successfully installed and set up this project. However, when I enter the Information of my iBeacon to test the functionality the first Tab (which is supposed to show the Log ) remains blank.

Here are the Logs from XCode:

    [44238:1635648] Registering delegate callback ID: LocationManager1223068201
    [44238:1635648] [DOM] _onDelegateCallback() null

and when Debugged in Safari:

    [Debug] startRanging() (ionic.bundle.js, line 17763)
    [Debug] Parsed BeaconRegion object: { (ionic.bundle.js, line 17763)
	"identifier": "beaconAtTheMacBooks",
	"uuid": "f0018b9b-7509-4c31-a905-1a27d39c003c",
	"major": 57591,
	"minor": 39029,
	"typeName": "BeaconRegion"
    }
    [Debug] EventLogCtrl is loaded. (ionic.bundle.js, line 17763)
    [Debug] Subscribing for updates of ranging events. (ionic.bundle.js, line 17763)

Help would be greatly appreciated.

**Comment by petermetz** [comment]
Hi @adrianmkofficial 

Sorry for the late response, you probably solved your issue in the meantime but still:
Did you check if bluetooth was enabled?
I would also try to restart the phone, re-install the application and other voodoo magic like things that come to mind.
And the obvious one: did you modify anything in the code at all, before running it?

If the issue is still relevant , feel free to re-open.


Peter
